version: '3.8'

services:
  app:
    container_name: simple-meal-app
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules # to avoid local node_modules being overwritten by the conatiner
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WATCHPACK_POLLING=true
  db:
    container_name: simple-meal-db
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Maan_2000
      POSTGRES_DB: simple_meal
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # Initialize the database with some tables and data
      - ./src/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/backend/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: