name: Build and Deploy

on:
  push:
    branches:
      - deploy
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          # List of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ env.REPO }}
          # List of tags as key-value pair attributes
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c  # v3.1.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # Sets the target stage to build
          target: production

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: read

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Sleep
        run: sleep 200
        shell: bash

      - name: Trigger a deployment
        uses: darnfish/watchtower-update@v3.2
        with:
          url: "${{ secrets.WATCHTOWER_URL }}"
          api_token: "${{ secrets.WATCHTOWER_API_TOKEN }}"
          images: "ghcr.io/${{ env.REPO }}:latest"
