# This workflow will build and push a Docker container to an Azure Web App when a commit is pushed to your branch.

name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: simplemeal  # set this to the name of your Azure Web App

on:
  push:
    branches:
      - deployment
      - deploy-to-azure
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          # List of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          # List of tags as key-value pair attributes
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c  # v3.1.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          # Path to the Dockerfile
          file: ./Dockerfile
          # Do not use cache when building the image
          no-cache: true
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: ${{ steps.meta.outputs.tags }}
          # Sets the target stage to build
          target: production

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:latest'
