name: Trigger auto deployment for simplemeal

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ deploy-to-azure ]
    paths:
    - '**'
    - '.github/workflows/simplemeal-AutoDeployTrigger-62ca6a7d-3370-425b-a594-fb9a344609e4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SIMPLEMEAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SIMPLEMEAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SIMPLEMEAL_AZURE_SUBSCRIPTION_ID }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.SIMPLEMEAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SIMPLEMEAL_REGISTRY_PASSWORD }}
          containerAppName: simplemeal
          resourceGroup: simplemeal_group
          ingress: external
          targetPort: 3000
          environmentVariables: 'REACT_APP_API_URL=https://api.simplemeal.live/ POSTGRES_USER=postgres POSTGRES_PASSWORD=secretref:pg-password POSTGRES_DB=postgres POSTGRES_HOST=simplemeal-db'
          imageToBuild: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


